# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
workspace 'BaseKit.xcworkspace'

target 'BaseKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BaseKit
	pod 'SnapKit'
end
target 'Demo' do
  project 'Demo/Demo.xcodeproj'
  # Comment the next line if you don't want to use dynamic framework
  use_frameworks!

  # Pods for BaseKit
  pod 'SnapKit'
end
target 'Demo-Objc' do
  project 'Demo-Objc/Demo-Objc.xcodeproj'
  # Comment the next line if you don't want to use dynamic framework
  use_frameworks!

  # Pods for BaseKit
  pod 'Masonry'
end
